//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openTill.Persistence
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Brand
    /// </summary>
    public partial class Brand
    {
        /// <summary>
        /// Product brand
        /// </summary>
        public Brand()
        {
            this.Products = new HashSet<Product>();
        }
        /// <summary>
        /// Brand ID
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Brand name
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Products
        /// </summary>
        public virtual ICollection<Product> Products { get; set; }
    }
}
