//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openTill.Persistence
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    /// <summary>
    /// Category
    /// </summary>
    public partial class Category
    {
        /// <summary>
        /// Product Category
        /// </summary>
        [ExcludeFromCodeCoverage]
        public Category()
        {
            this.ProductCategories = new HashSet<ProductCategory>();
        }
        /// <summary>
        /// Category ID
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Category Name
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Category Description
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Product Categories
        /// </summary>
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
    }
}
