//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openTill.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public int PositionId { get; set; }
        public int AddressId { get; set; }
        public int PhoneId { get; set; }
        public decimal Wage { get; set; }
        public int SSN { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> PasswordHash { get; set; }
        public Nullable<System.Guid> PinHash { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual Position Position { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
