//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openTill.Persistence
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Employee Phone
    /// </summary>
    public partial class Phone
    {
        /// <summary>
        /// Employee Phone
        /// </summary>
        public Phone()
        {
            this.Employees = new HashSet<Employee>();
        }
        /// <summary>
        /// Phone ID
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Phone Number
        /// </summary>
        public string PhoneNumber { get; set; }
        /// <summary>
        /// Employee
        /// </summary>
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
