//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openTill.Persistence
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    /// <summary>
    /// Employee Position
    /// </summary>
    public partial class Position
    {
        /// <summary>
        /// Position
        /// </summary>
        [ExcludeFromCodeCoverage]
        public Position()
        {
            this.Employees = new HashSet<Employee>();
        }
        /// <summary>
        /// Position ID
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Position Name
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Position Description
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Employees
        /// </summary>
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
