//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openTill.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductCategories = new HashSet<ProductCategory>();
            this.SaleItems = new HashSet<SaleItem>();
        }
    
        public string UPC { get; set; }
        public int BrandId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal StoreCost { get; set; }
        public decimal SellingPrice { get; set; }
        public int OnHand { get; set; }
        public int MinOnHand { get; set; }
        public bool HasDeposit { get; set; }
        public bool IsTaxable { get; set; }
        public Nullable<byte> MinimumAge { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        public virtual ICollection<SaleItem> SaleItems { get; set; }
    }
}
