//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openTill.Persistence
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Sale Item
    /// </summary>
    public partial class SaleItem
    {
        /// <summary>
        /// Sale Item ID
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Sale ID
        /// </summary>
        public int SaleId { get; set; }
        /// <summary>
        /// Product ID
        /// </summary>
        public string ProductId { get; set; }
        /// <summary>
        /// How many?
        /// </summary>
        public int Quantity { get; set; }
        /// <summary>
        /// Product
        /// </summary>
        public virtual Product Product { get; set; }
        /// <summary>
        /// Sale
        /// </summary>
        public virtual Sale Sale { get; set; }
    }
}
