//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openTill.Persistence
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    /// <summary>
    /// State
    /// </summary>
    public partial class State
    {
        /// <summary>
        /// State Address
        /// </summary>
        [ExcludeFromCodeCoverage]
        public State()
        {
            this.Addresses = new HashSet<Address>();
        }
        /// <summary>
        /// State ID
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Full State Name
        /// </summary>
        public string FullStateName { get; set; }
        /// <summary>
        /// Abbreviated State Name
        /// </summary>
        public string AbbreviatedStateName { get; set; }
        /// <summary>
        /// Addresses
        /// </summary>
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
