//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openTill.Persistence
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    /// <summary>
    /// Zip Code
    /// </summary>
    public partial class ZipCode
    {
        /// <summary>
        /// Zip Code
        /// </summary>
        [ExcludeFromCodeCoverage]
        public ZipCode()
        {
            this.Addresses = new HashSet<Address>();
        }
        /// <summary>
        /// Zip Code ID
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Zip Code
        /// </summary>
        public string ZipCode1 { get; set; }
        /// <summary>
        /// Address
        /// </summary>
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
